apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ll407fnxr-go 
  janus-idp.io/tekton: ll407fnxr-go
  backstage.io/kubernetes-id: ll407fnxr-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ll407fnxr-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  